import { ProjectSummary } from "@/domain/projects/types";
import { TaskItem } from "@/domain/tasks/types";
import { InvoiceItem, PaymentItem } from "@/domain/payments/types";
import { AuditLogItem } from "@/domain/audit/types";

export interface AppState {
  currentWorkspace: {
    id: string;
    name: string;
    slug: string;
    timezone: string;
    enforcePaymentGate: boolean;
    enforceAgreementGate: boolean;
  };
  currentUser: {
    id: string;
    name: string;
    email: string;
    avatarUrl: string | null;
    globalRole: "SUPER_ADMIN" | "ADMIN" | "FINANCE" | "VIEWER" | "STAFF";
    actingProjectRole: "PROJECT_MANAGER" | "DESIGNER" | "DEVELOPER" | "FREELANCER" | "CLIENT" | "ADMIN";
  };
  projects: ProjectSummary[];
  tasks: TaskItem[];
  invoices: InvoiceItem[];
  payments: PaymentItem[];
  auditLogs: AuditLogItem[];
  notifications: Array<{
    id: string;
    title: string;
    message: string;
    priority: "CRITICAL" | "HIGH" | "NORMAL" | "LOW";
    entityType: string;
    entityId: string;
    actionUrl?: string;
    isRead: boolean;
    createdAt: string;
  }>;
}

export const initialMockState: AppState = {
  currentWorkspace: {
    id: "ws-indian-pixel",
    name: "Indian Pixel Studio",
    slug: "indian-pixel",
    timezone: "Asia/Kolkata",
    enforcePaymentGate: true,
    enforceAgreementGate: true,
  },
  currentUser: {
    id: "user-super-admin",
    name: "Krishna Mishra",
    email: "krishna@indianpixel.com",
    avatarUrl: null,
    globalRole: "SUPER_ADMIN",
    actingProjectRole: "ADMIN",
  },
  projects: [
    {
      id: "proj-mitti",
      workspaceId: "ws-indian-pixel",
      clientId: "client-mitti",
      clientName: "Mitti & Co.",
      pmId: "user-pm-1",
      pmName: "Aarav Sharma",
      name: "Mitti & Co. Brand Refresh & Packaging",
      description: "Artisanal natural textures, earth-toned packaging, and multi-channel eCommerce identity.",
      status: "ACTIVE",
      startDate: "2026-07-01",
      targetDate: "2026-09-15",
      servicesCount: 3,
      completedServicesCount: 1,
      tasksCount: 14,
      completedTasksCount: 9,
      overdueTasksCount: 1,
      stalledApprovalsCount: 1,
      reopenCount: 0,
      createdAt: "2026-07-01T10:00:00Z",
      updatedAt: "2026-08-08T15:30:00Z",
    },
    {
      id: "proj-vally",
      workspaceId: "ws-indian-pixel",
      clientId: "client-vally",
      clientName: "Vally & Hound",
      pmId: "user-pm-1",
      pmName: "Aarav Sharma",
      name: "Vally & Hound Luxury Outdoors Identity",
      description: "Rugged nature meets high-end luxury aesthetics with 3D product motion graphics.",
      status: "ACTIVE",
      startDate: "2026-06-15",
      targetDate: "2026-08-30",
      servicesCount: 4,
      completedServicesCount: 2,
      tasksCount: 20,
      completedTasksCount: 17,
      overdueTasksCount: 0,
      stalledApprovalsCount: 0,
      reopenCount: 1,
      createdAt: "2026-06-15T09:00:00Z",
      updatedAt: "2026-08-07T12:00:00Z",
    },
    {
      id: "proj-tech-sol",
      workspaceId: "ws-indian-pixel",
      clientId: "client-tech-sol",
      clientName: "Tech Solutions Inc.",
      pmId: "user-pm-2",
      pmName: "Priya Patel",
      name: "SaaS Design System & Marketing Site",
      description: "Complete design tokens, responsive web application UI, and conversion landing pages.",
      status: "ACTIVE",
      startDate: "2026-05-10",
      targetDate: "2026-08-10",
      servicesCount: 2,
      completedServicesCount: 1,
      tasksCount: 18,
      completedTasksCount: 15,
      overdueTasksCount: 2,
      stalledApprovalsCount: 1,
      reopenCount: 0,
      createdAt: "2026-05-10T11:00:00Z",
      updatedAt: "2026-08-08T14:15:00Z",
    },
  ],
  tasks: [
    {
      id: "task-101",
      workspaceId: "ws-indian-pixel",
      milestoneId: "ms-packaging",
      milestoneName: "Primary Box Packaging Design",
      projectId: "proj-mitti",
      projectName: "Mitti & Co. Brand Refresh & Packaging",
      clientName: "Mitti & Co.",
      assigneeId: "user-designer-1",
      assigneeName: "Rohan Verma",
      name: "Matte Foil Emboss Print Specifications",
      description: "Prepare 300DPI vector die-lines with pantone metallic gold foil separations.",
      status: "IN_PROGRESS",
      dueDate: "2026-08-05", // Overdue!
      isOverdue: true,
      blockedReason: null,
      deliverablesCount: 1,
      hasRejectedDeliverable: false,
      createdAt: "2026-07-20T10:00:00Z",
      updatedAt: "2026-08-06T09:00:00Z",
    },
    {
      id: "task-102",
      workspaceId: "ws-indian-pixel",
      milestoneId: "ms-packaging",
      milestoneName: "Primary Box Packaging Design",
      projectId: "proj-mitti",
      projectName: "Mitti & Co. Brand Refresh & Packaging",
      clientName: "Mitti & Co.",
      assigneeId: "user-designer-1",
      assigneeName: "Rohan Verma",
      name: "3D Product Render in Amber Glass Jar",
      description: "High-resolution raytraced studio lighting render for client presentation.",
      status: "SUBMITTED_FOR_VERIFICATION",
      dueDate: "2026-08-12",
      isOverdue: false,
      blockedReason: null,
      deliverablesCount: 2,
      hasRejectedDeliverable: false,
      createdAt: "2026-07-22T11:00:00Z",
      updatedAt: "2026-08-08T10:30:00Z",
    },
    {
      id: "task-103",
      workspaceId: "ws-indian-pixel",
      milestoneId: "ms-tokens",
      milestoneName: "Enterprise Design Tokens & Typography",
      projectId: "proj-tech-sol",
      projectName: "SaaS Design System & Marketing Site",
      clientName: "Tech Solutions Inc.",
      assigneeId: "user-dev-1",
      assigneeName: "Ananya Iyer",
      name: "Dark/Light Tailwind Color Variables Implementation",
      description: "Verify WCAG 2.2 AA contrast ratios and export tokens to Figma Sync.",
      status: "COMPLETE",
      dueDate: "2026-08-01",
      isOverdue: false,
      blockedReason: null,
      deliverablesCount: 1,
      hasRejectedDeliverable: false,
      createdAt: "2026-07-15T09:00:00Z",
      updatedAt: "2026-08-02T14:00:00Z",
    },
    {
      id: "task-104",
      workspaceId: "ws-indian-pixel",
      milestoneId: "ms-motion",
      milestoneName: "3D Motion Reveal Teaser",
      projectId: "proj-vally",
      projectName: "Vally & Hound Luxury Outdoors Identity",
      clientName: "Vally & Hound",
      assigneeId: "user-freelance-1",
      assigneeName: "Vikram Sengupta",
      name: "Audio Stems & Sound Design Mix",
      description: "Mastered 48kHz spatial stereo track accompanying the logo particle animation.",
      status: "IN_PROGRESS",
      dueDate: "2026-08-15",
      isOverdue: false,
      blockedReason: null,
      deliverablesCount: 1,
      hasRejectedDeliverable: false,
      createdAt: "2026-07-28T16:00:00Z",
      updatedAt: "2026-08-07T11:00:00Z",
    },
  ],
  invoices: [
    {
      id: "inv-2026-001",
      workspaceId: "ws-indian-pixel",
      projectId: "proj-mitti",
      projectName: "Mitti & Co. Brand Refresh & Packaging",
      clientName: "Mitti & Co.",
      milestoneId: "ms-packaging",
      milestoneName: "Primary Box Packaging Design",
      invoiceNumber: "INV-2026-001",
      amount: 15000000, // 1,50,000 INR
      currency: "INR",
      status: "ISSUED",
      dueDate: "2026-08-10",
      paidAmount: 0,
      remainingBalance: 15000000,
      isOverdue: false,
      issuedAt: "2026-07-25T10:00:00Z",
      paidAt: null,
      createdAt: "2026-07-25T10:00:00Z",
    },
    {
      id: "inv-2026-002",
      workspaceId: "ws-indian-pixel",
      projectId: "proj-tech-sol",
      projectName: "SaaS Design System & Marketing Site",
      clientName: "Tech Solutions Inc.",
      milestoneId: "ms-tokens",
      milestoneName: "Enterprise Design Tokens & Typography",
      invoiceNumber: "INV-2026-002",
      amount: 22000000, // 2,20,000 INR
      currency: "INR",
      status: "OVERDUE",
      dueDate: "2026-08-01",
      paidAmount: 5000000, // 50,000 INR
      remainingBalance: 17000000,
      isOverdue: true,
      issuedAt: "2026-07-15T09:00:00Z",
      paidAt: null,
      createdAt: "2026-07-15T09:00:00Z",
    },
    {
      id: "inv-2026-003",
      workspaceId: "ws-indian-pixel",
      projectId: "proj-vally",
      projectName: "Vally & Hound Luxury Outdoors Identity",
      clientName: "Vally & Hound",
      milestoneId: "ms-motion",
      milestoneName: "3D Motion Reveal Teaser",
      invoiceNumber: "INV-2026-003",
      amount: 30000000, // 3,00,000 INR
      currency: "INR",
      status: "PAID",
      dueDate: "2026-07-20",
      paidAmount: 30000000,
      remainingBalance: 0,
      isOverdue: false,
      issuedAt: "2026-07-05T09:00:00Z",
      paidAt: "2026-07-18T14:30:00Z",
      createdAt: "2026-07-05T09:00:00Z",
    },
  ],
  payments: [
    {
      id: "pay-101",
      workspaceId: "ws-indian-pixel",
      projectId: "proj-vally",
      projectName: "Vally & Hound Luxury Outdoors Identity",
      invoiceId: "inv-2026-003",
      invoiceNumber: "INV-2026-003",
      milestoneId: "ms-motion",
      amount: 30000000,
      currency: "INR",
      status: "RECONCILED",
      paymentMethod: "NEFT / RTGS",
      referenceNumber: "UTR98234120938",
      recordedById: "user-finance",
      recordedByName: "Neha Kulkarni",
      disputeReason: null,
      refundId: null,
      createdAt: "2026-07-18T14:30:00Z",
    },
    {
      id: "pay-102",
      workspaceId: "ws-indian-pixel",
      projectId: "proj-tech-sol",
      projectName: "SaaS Design System & Marketing Site",
      invoiceId: "inv-2026-002",
      invoiceNumber: "INV-2026-002",
      milestoneId: "ms-tokens",
      amount: 5000000,
      currency: "INR",
      status: "RECORDED",
      paymentMethod: "UPI / Corporate Card",
      referenceNumber: "UPI-4098239023",
      recordedById: "user-finance",
      recordedByName: "Neha Kulkarni",
      disputeReason: null,
      refundId: null,
      createdAt: "2026-07-28T11:20:00Z",
    },
  ],
  auditLogs: [
    {
      id: "audit-001",
      workspaceId: "ws-indian-pixel",
      actorId: "user-super-admin",
      actorName: "Krishna Mishra (Super Admin)",
      actorType: "USER",
      entityType: "Workspace",
      entityId: "ws-indian-pixel",
      entityName: "Indian Pixel Studio",
      action: "workspace.configured",
      priorState: null,
      newState: "PaymentGate=Enforced, AgreementGate=Enforced",
      justification: "Initial workspace launch setup",
      amount: null,
      currency: null,
      timestamp: "2026-08-08T18:00:00Z",
    },
    {
      id: "audit-002",
      workspaceId: "ws-indian-pixel",
      actorId: "user-pm-1",
      actorName: "Aarav Sharma (PM)",
      actorType: "USER",
      entityType: "Milestone",
      entityId: "ms-packaging",
      entityName: "Primary Box Packaging Design",
      action: "milestone.submitted_for_approval",
      priorState: "IN_PROGRESS",
      newState: "SUBMITTED_FOR_APPROVAL",
      justification: null,
      amount: null,
      currency: null,
      timestamp: "2026-08-08T14:20:00Z",
    },
    {
      id: "audit-003",
      workspaceId: "ws-indian-pixel",
      actorId: "System (Overdue Flagging Process)",
      actorName: "Overdue Flagging Process",
      actorType: "SYSTEM_PROCESS",
      entityType: "Task",
      entityId: "task-101",
      entityName: "Matte Foil Emboss Print Specifications",
      action: "task.auto_flagged_overdue",
      priorState: "isOverdue=false",
      newState: "isOverdue=true",
      justification: "Due date 2026-08-05 elapsed with balance work",
      amount: null,
      currency: null,
      timestamp: "2026-08-06T00:00:00Z",
    },
    {
      id: "audit-004",
      workspaceId: "ws-indian-pixel",
      actorId: "user-finance",
      actorName: "Neha Kulkarni (Finance)",
      actorType: "USER",
      entityType: "Payment",
      entityId: "pay-101",
      entityName: "NEFT UTR98234120938",
      action: "payment.reconciled",
      priorState: "RECORDED",
      newState: "RECONCILED",
      justification: "Bank credit verified on HDFC portal",
      amount: 30000000,
      currency: "INR",
      timestamp: "2026-07-18T14:35:00Z",
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Task Overdue: Matte Foil Emboss Print Specifications",
      message: "Task is 3 days past due under Mitti & Co. Milestone. Immediate PM attention requested.",
      priority: "HIGH",
      entityType: "Task",
      entityId: "task-101",
      actionUrl: "/projects/proj-mitti?tab=tasks",
      isRead: false,
      createdAt: "2026-08-06T00:01:00Z",
    },
    {
      id: "notif-2",
      title: "Invoice Overdue: INV-2026-002 (Tech Solutions Inc.)",
      message: "Balance of ₹1,70,000 is overdue since 2026-08-01. Payment gate may restrict upcoming milestones.",
      priority: "CRITICAL",
      entityType: "Invoice",
      entityId: "inv-2026-002",
      actionUrl: "/payments?invoiceId=inv-2026-002",
      isRead: false,
      createdAt: "2026-08-02T00:00:00Z",
    },
    {
      id: "notif-3",
      title: "Milestone Ready for Client Approval",
      message: "Aarav Sharma submitted 'Primary Box Packaging Design' for formal client sign-off.",
      priority: "HIGH",
      entityType: "Milestone",
      entityId: "ms-packaging",
      actionUrl: "/projects/proj-mitti?tab=milestones&approval=ms-packaging",
      isRead: false,
      createdAt: "2026-08-08T14:20:00Z",
    },
  ],
};
